### ISSUE TITLE
When a consumer is deleted from the server, NACK does not recreate it

### ISSUE THREAD

**Issue by rozidan** [nats-io/nack#167] opened 2024-02-05 10:49 UTC
### What version were you using?

NACK: 0.14.1
Nats-server: 2.10.9

### What environment was the server running in?

RKE2: v1.26.4+rke2r1

### Is this defect reproducible?

1. Create consumer with nack
2. The consumer has been successfully created on the NATS server.
3. Delete the consumer with nats-box 
4. Restart NACK

### Given the capability you are leveraging, describe your expectation?

The consumer should be recreated

### Given the expectation, what is the defect you are observing?

The consumer is not recreated
nack log: 
"type: 'Normal' reason: 'Noop' Nothing done for consumer..."

Please see a similar issue fixed as part of #162 for streams

**Comment by Jarema** [comment] 2024-02-05 11:06
Thanks for opening the issue.
This is part of consideration for the Future of NACK, as right now it does not have reconcile loop.
For more details and discussion, check the discussion: #166

**Comment by jorgelon** [comment] 2024-02-08 12:25
same for a stream

`kubectl logs nack-XXXXXXX`

`Nothing done for stream "XXXX" (prevent-delete=false, prevent-update=false)`

I have to delete the object and recreate it

**Comment by Jarema** [comment] 2024-02-08 12:39
This is something we work on while moving forward #166 

This is not a bug - the NACK does not have a reconcile loop to act on changes.
The new version of it will fully support it.

**Comment by Jarema** [comment] 2024-02-15 09:52
Yes, the fix will be part of the next release. I need to take a look into the consumer code if the same easy fix can be applied.

**Comment by svenfoo** [comment] 2024-06-18 11:10
Ran into this problem with v0.14.4 now. It looks like [the code in `consumer.go`](https://github.com/nats-io/nack/blob/c6ca1ed7cbddfecdfec472008103d9a0525a180a/controllers/jetstream/consumer.go#L196) needs a similar change than what was fixed in `stream.go` [recently](https://github.com/nats-io/nack/commit/c6ca1ed7cbddfecdfec472008103d9a0525a180a).

**Comment by svenfoo** [comment] 2024-06-20 13:12
> Yes, the fix will be part of the next release. I need to take a look into the consumer code if the same easy fix can be applied.

@Jarema Did you ever do this? To me it looks like the consumer code just needs the same easy fix. But I might be wrong, of course.

**Comment by Jarema** [comment] 2024-06-24 07:01
I realized that it was done only for streams.
Need to add the same behavior to the consumer.

**Closed as completed** 2024-07-02 09:16 UTC
Labels: defect
