### ISSUE TITLE
Deleting a nats cluster pod results in peer log: error sending snapshot to follower [xyz]: raft: no snapshot available 

### ISSUE THREAD

**Issue by bajoben** [nats-io/nack#64] opened 2022-02-24 13:32 UTC
###### Issue:
When killing the stream leader of a nats jetstream cluster it seems like **RAFT** is not synchronizing perfectly. After the deleted peer (which is typically a statefulset pod like nats-0, nats-1, nats-2, nats-n) is recovered it throws the warning ```JetStream cluster consumer '$G > data> some_durable-connection' has NO quorum, stalled.``` . While the not deleted peers (pods) throw the logged error ```Error sending snapshot to follower [xyz]: raft: no snapshot available```

This issue results in an not corret working stream. It seems like that the clients are not connected to Jetstream in a correct manner.

When requesting consumer info in nats-box, the following is printed out.
```error: could not load Consumer consumer-xyz > consumer_durable-connection: JetStream system temporarily unavailable (10008)```

```
╭─────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                   Stream Report                                                 │
├──────────┬─────────┬───────────┬──────────┬─────────┬──────┬─────────┬──────────────────────────┤
│ Stream   │ Storage │ Consumers │ Messages │ Bytes   │ Lost │ Deleted │ Replicas                 │
├──────────┼─────────┼───────────┼──────────┼─────────┼──────┼─────────┼──────────────────────────┤
│ stream-1 │ Memory  │ 2         │ 23,753   │ 48 MiB  │ 0    │ 0       │ nats-0, nats-1, nats-2*  │
│ stream-2 │ Memory  │ 1         │ 91,459   │ 238 MiB │ 0    │ 0       │ nats-0, nats-1!, nats-2* │
│ stream-3 │ Memory  │ 4         │ 201,431  │ 477 MiB │ 0    │ 0       │ nats-0, nats-1, nats-2*  │
╰──────────┴─────────┴───────────┴──────────┴─────────┴──────┴─────────┴──────────────────────────╯
```

###### Experienced with:
Kubernetes 1.21.2 with nats jetstream cluster (3 and 5 statefulset pods) and 3 streams (3 Replicas each), nats jetstream 2.7.2, java client with jnats 2.13.2
nats jetstream was istalled via offical helm chart. 

###### Reproduce: 
kill peer pod which is marked as current leader for a stream (kubectl delete pod), checking the peer pod logs.

**Comment by blanorama** [comment] 2022-02-24 13:51
```
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                 Stream Report                                                 │
├────────────────────────┬─────────┬───────────┬──────────┬─────────┬──────┬─────────┬──────────────────────────┤
│ Stream                 │ Storage │ Consumers │ Messages │ Bytes   │ Lost │ Deleted │ Replicas                 │
├────────────────────────┼─────────┼───────────┼──────────┼─────────┼──────┼─────────┼──────────────────────────┤
│ plutos-live-data       │ Memory  │ 2         │ 23,753   │ 48 MiB  │ 0    │ 0       │ nats-0, nats-1, nats-2*  │
│ plutos-dead-letter     │ Memory  │ 1         │ 91,459   │ 238 MiB │ 0    │ 0       │ nats-0, nats-1!, nats-2* │
│ plutos-historical-data │ Memory  │ 4         │ 201,431  │ 477 MiB │ 0    │ 0       │ nats-0, nats-1, nats-2*  │
╰────────────────────────┴─────────┴───────────┴──────────┴─────────┴──────┴─────────┴──────────────────────────╯
```

**Comment by blanorama** [comment] 2022-02-24 13:55
another try to get it beautifed 🙈 
```
╭─────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                   Stream Report                                                 │
├──────────┬─────────┬───────────┬──────────┬─────────┬──────┬─────────┬──────────────────────────┤
│ Stream   │ Storage │ Consumers │ Messages │ Bytes   │ Lost │ Deleted │ Replicas                 │
├──────────┼─────────┼───────────┼──────────┼─────────┼──────┼─────────┼──────────────────────────┤
│ stream-1 │ Memory  │ 2         │ 23,753   │ 48 MiB  │ 0    │ 0       │ nats-0, nats-1, nats-2*  │
│ stream-2 │ Memory  │ 1         │ 91,459   │ 238 MiB │ 0    │ 0       │ nats-0, nats-1!, nats-2* │
│ stream-3 │ Memory  │ 4         │ 201,431  │ 477 MiB │ 0    │ 0       │ nats-0, nats-1, nats-2*  │
╰──────────┴─────────┴───────────┴──────────┴─────────┴──────┴─────────┴──────────────────────────╯
```

**Comment by bajoben** [comment] 2022-03-09 11:04
hi guys, could you at least reproduce it or do i have to provide more information.

**Comment by furkansb** [comment] 2022-03-24 15:15
We have the exact same problem. Is there any update on this? If Jetstream stays like this, I don't think it is reliable to use on production in a Kubernetes cluster.

**Comment by derekcollison** [comment] 2022-03-25 16:48
Does the same issue present with 2.7.4, our latest release? We are nearing the release of 2.8.0 as well. Might be worth checking out the release notes, etc.

Also there was a bug we discovered just recently that will allow a stream to take over as a leader when it was still trying to catch up, causing some instability in the system. We observed this under similar situations where pods were being randomly deleted or migrated during a user's torture test.

That code has been fixed, is in main and nightly and will be part of 2.8.0.

I will try to recreate. A few questions.

1. Are messages still flowing into the system as you delete the pods?
2. Do the pods automatically come back up? The updated help chart IIRC will watch for /healthz to return ok.
3. What does `nats stream info` report for those streams? (NATS cli which is the preferred method to interact with the system non-programatically).
4. How many consumers per stream? What does `nats consumer info` show for those?

Thanks for your patience.

**Comment by furkansb** [comment] 2022-03-25 22:45
I've reproduced the same issue with 2.7.4 release. We have a test cluster so we can try 2.8.0 too when it gets released.

1. Yes, problem rises when new cluster node tries to join the cluster and other members of the cluster can't send the snapshot to new member.
2. Yes, pods automatically come back up.
3. It doesn't show anything unusual. Do you expect anything specific? 
4. 10 consumers per stream. It logs an error: 
`nats: error: could not load Consumer audio > audio-34: JetStream system temporarily unavailable (10008)`

Thanks for your help!

**Comment by derekcollison** [comment] 2022-03-27 23:53
If the storage is not a persisted volume the raft logs backing the memory stream will be lost..

**Comment by derekcollison** [comment] 2022-03-28 00:05
For instance, just running a 3 node cluster on my machine, creating a R3 memory stream and putting 100k messages in it, then killing S1 (but it has a storage directory). Restarting it immediately recreates the last replica for the stream.

If I kill it and remove the storage directory contents for S1, still works fine for me.

However, if I kill S1, remove the storage directory and allow the new server to pick a new name (server_name), or I allow it to pick one itself, it complains about meta raft snapshots and the `nats stream info TEST` always shows the replica OFFLINE.

Possible the server names are not consistent in this scenario?

**Comment by furkansb** [comment] 2022-03-28 11:05
Storage is persisted within a PVC in Kubernetes. 

Server names are consistent because we installed the Nats Jetstream Cluster via Helm chart which uses StatefulSets in Kubernetes. That gives every pod a unique non-changing name. For example:

```
Jetstream Cluster member 1 server/pod name: nats-jetstream-0
Jetstream Cluster member 2 server/pod name: nats-jetstream-1
Jetstream Cluster member 3 server/pod name: nats-jetstream-2
```

Also, this is the config I'm using for Jetstream deployment:
https://gist.github.com/furkansb/e74384d3119935783bf80cced3ff2176

**Comment by derekcollison** [comment] 2022-03-28 13:20
Ah, ok my apologies. Will take a look at config.

**Comment by derekcollison** [comment] 2022-03-28 13:24
Hey @caleblloyd and @wallyqs could you look at the config used above, I placed some comments there and was curious.

**Comment by wallyqs** [comment] 2023-01-06 08:46
Reported as fixed here: https://gist.github.com/furkansb/e74384d3119935783bf80cced3ff2176?permalink_comment_id=4141623#gistcomment-4141623

**Closed by wallyqs** 2023-01-06 08:46 UTC
